name: PR Merged
on: 
  pull_request:
    types: [closed]
    branches:
      - 'master'
    
jobs:
  Test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Check if PR is merged
      if: github.event.pull_request.merged == true
      run: echo "PR is merged to ${GITHUB_REF##*/}" 

    - name: Tasks List
      run: date
